### ISSUE TITLE
Return all bonding withdraws under delegator in one time

### ISSUE THREAD

**Issue by wanghao926** [QOSGroup/litewallet#11]
请提供一键取回该delegator下所有分红接口

**Comment by MattWangming** [comment]
To be delivered in the comming commits~

**Comment by MattWangming** [comment]
目前已有接口GetAllDelegations，GetAllUnbondingDelegations，GetDelegtorRewardsShares分别查询delegator所有的委托，赎回期委托和待取分红

**Comment by MattWangming** [comment]
Only the new func `WithdrawDelegatorAllRewards` is in need for the new commit

**Comment by MattWangming** [comment]
@wanghao926 To be testified...

**Comment by MattWangming** [comment]
<img width="1068" alt="bug" src="https://user-images.githubusercontent.com/37991051/58679986-5c668100-8398-11e9-9cf8-332844bb4013.png">

**Comment by MattWangming** [comment]
a new bug found here

**Comment by MattWangming** [comment]
@wangkuanzzu setup testnet with multi-validator nodes for testing with func withdraw all rewards from all the delegated validators.
The testnet is uniformed deployed in `vagrant@192.168.1.184`. Please take steps to setup multi-validaotrs.

**Comment by wangkuanzzu** [comment]
···
[vagrant@vagrant-192-168-1-201 ~]$ ./gaiacli query tendermint-validator-set --chain-id cosmosv34
block height: 764941

  Address:          cosmosvalcons1z9wj5dhy82ua2t5w4ecslqa2n93pv85x6p0jv9
  Pubkey:           cosmosvalconspub1zcjduepqw5f4nvar2ktxpdlm0uxef0mezx8rk3g3vns8ngsfsy5se80rrhhqcjgexu
  ProposerPriority: 84
  VotingPower:      178
		
  Address:          cosmosvalcons1k92y9rugvglvksh9phtajhwt7qxd9md9s5j6vz
  Pubkey:           cosmosvalconspub1zcjduepqjvsy7qnt79aq3f6mnqtg6aq8e9zattn7j7k5qgj7upswzp5nmrxqe28x0s
  ProposerPriority: -83
  VotingPower:      1
		
[vagrant@vagrant-192-168-1-201 ~]$ ./gaiacli query tendermint-validator-set --chain-id cosmosv34
block height: 764976

  Address:          cosmosvalcons1z9wj5dhy82ua2t5w4ecslqa2n93pv85x6p0jv9
  Pubkey:           cosmosvalconspub1zcjduepqw5f4nvar2ktxpdlm0uxef0mezx8rk3g3vns8ngsfsy5se80rrhhqcjgexu
  ProposerPriority: 108
  VotingPower:      178
		
  Address:          cosmosvalcons1k92y9rugvglvksh9phtajhwt7qxd9md9s5j6vz
  Pubkey:           cosmosvalconspub1zcjduepqjvsy7qnt79aq3f6mnqtg6aq8e9zattn7j7k5qgj7upswzp5nmrxqe28x0s
  ProposerPriority: 19
  VotingPower:      1
		
  Address:          cosmosvalcons1cuv8c79k2shccwltvuu5v47m4lvy8qv3xccy6n
  Pubkey:           cosmosvalconspub1zcjduepqs0nusd594xcszrk4lqkd22qtp268lfp5dlqqzdkm360fnfvwngxsv6dq7y
  ProposerPriority: -127
  VotingPower:      1

···

**Comment by wangkuanzzu** [comment]
‘’‘
[vagrant@vagrant-192-168-1-201 ~]$ ./gaiacli query tendermint-validator-set --chain-id cosmosv34
block height: 764941

  Address:          cosmosvalcons1z9wj5dhy82ua2t5w4ecslqa2n93pv85x6p0jv9
  Pubkey:           cosmosvalconspub1zcjduepqw5f4nvar2ktxpdlm0uxef0mezx8rk3g3vns8ngsfsy5se80rrhhqcjgexu
  ProposerPriority: 84
  VotingPower:      178
		
  Address:          cosmosvalcons1k92y9rugvglvksh9phtajhwt7qxd9md9s5j6vz
  Pubkey:           cosmosvalconspub1zcjduepqjvsy7qnt79aq3f6mnqtg6aq8e9zattn7j7k5qgj7upswzp5nmrxqe28x0s
  ProposerPriority: -83
  VotingPower:      1
		
[vagrant@vagrant-192-168-1-201 ~]$ ./gaiacli query tendermint-validator-set --chain-id cosmosv34
block height: 764976

  Address:          cosmosvalcons1z9wj5dhy82ua2t5w4ecslqa2n93pv85x6p0jv9
  Pubkey:           cosmosvalconspub1zcjduepqw5f4nvar2ktxpdlm0uxef0mezx8rk3g3vns8ngsfsy5se80rrhhqcjgexu
  ProposerPriority: 108
  VotingPower:      178
		
  Address:          cosmosvalcons1k92y9rugvglvksh9phtajhwt7qxd9md9s5j6vz
  Pubkey:           cosmosvalconspub1zcjduepqjvsy7qnt79aq3f6mnqtg6aq8e9zattn7j7k5qgj7upswzp5nmrxqe28x0s
  ProposerPriority: 19
  VotingPower:      1
		
  Address:          cosmosvalcons1cuv8c79k2shccwltvuu5v47m4lvy8qv3xccy6n
  Pubkey:           cosmosvalconspub1zcjduepqs0nusd594xcszrk4lqkd22qtp268lfp5dlqqzdkm360fnfvwngxsv6dq7y
  ProposerPriority: -127
  VotingPower:      1

‘’’

**Comment by wangkuanzzu** [comment]
> 
[vagrant@vagrant-192-168-1-201 ~]$ ./gaiacli query tendermint-validator-set --chain-id cosmosv34
block height: 764941

  Address:          cosmosvalcons1z9wj5dhy82ua2t5w4ecslqa2n93pv85x6p0jv9
  Pubkey:           cosmosvalconspub1zcjduepqw5f4nvar2ktxpdlm0uxef0mezx8rk3g3vns8ngsfsy5se80rrhhqcjgexu
  ProposerPriority: 84
  VotingPower:      178
		
  Address:          cosmosvalcons1k92y9rugvglvksh9phtajhwt7qxd9md9s5j6vz
  Pubkey:           cosmosvalconspub1zcjduepqjvsy7qnt79aq3f6mnqtg6aq8e9zattn7j7k5qgj7upswzp5nmrxqe28x0s
  ProposerPriority: -83
  VotingPower:      1
		
[vagrant@vagrant-192-168-1-201 ~]$ ./gaiacli query tendermint-validator-set --chain-id cosmosv34
block height: 764976

  Address:          cosmosvalcons1z9wj5dhy82ua2t5w4ecslqa2n93pv85x6p0jv9
  Pubkey:           cosmosvalconspub1zcjduepqw5f4nvar2ktxpdlm0uxef0mezx8rk3g3vns8ngsfsy5se80rrhhqcjgexu
  ProposerPriority: 108
  VotingPower:      178
		
  Address:          cosmosvalcons1k92y9rugvglvksh9phtajhwt7qxd9md9s5j6vz
  Pubkey:           cosmosvalconspub1zcjduepqjvsy7qnt79aq3f6mnqtg6aq8e9zattn7j7k5qgj7upswzp5nmrxqe28x0s
  ProposerPriority: 19
  VotingPower:      1
		
  Address:          cosmosvalcons1cuv8c79k2shccwltvuu5v47m4lvy8qv3xccy6n
  Pubkey:           cosmosvalconspub1zcjduepqs0nusd594xcszrk4lqkd22qtp268lfp5dlqqzdkm360fnfvwngxsv6dq7y
  ProposerPriority: -127
  VotingPower:      1

> 

>

**Comment by MattWangming** [comment]
close with positive feedback.
