### ISSUE TITLE
ethTransferETH金额超出long类数值范围

### ISSUE THREAD

**Issue by yangchuang64** [QOSGroup/litewallet#15]

**Comment by MattWangming** [comment]
This could be adjusted to convert input ***amount*** of fun `TransferETH` to string type instead of current int64.

**Comment by yangchuang64** [comment]
[https://kovan.etherscan.io/tx/0x542180d4a9740781f8414ce92e4d5409493e88f1e5b5f0e921141c30ba53e535](url)
转账0.001个Eth，在etherscan看到的是0.001000000047497451

**Comment by MattWangming** [comment]
there is bug here need to be fixed asap!

**Comment by MattWangming** [comment]
close with posotive feedback
