### ISSUE TITLE
连续转账奔溃

### ISSUE THREAD

**Issue by yangchuang64** [QOSGroup/litewallet#22]
06-06 16:38:16.306 E/Go      (27757): panic: runtime error: invalid memory address or nil pointer dereference
06-06 16:38:16.306 E/Go      (27757): [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0xcae91e5c]
06-06 16:38:16.306 E/Go      (27757):
06-06 16:38:16.306 E/Go      (27757): goroutine 17 [running, locked to thread]:
06-06 16:38:16.306 E/GoLog   (27757): panic: runtime error: invalid memory address or nil pointer dereference
06-06 16:38:16.306 E/GoLog   (27757): [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0xcae91e5c]
06-06 16:38:16.306 E/Go      (27757): github.com/QOSGroup/litewallet/litewallet/eth.TransferETH(0x99eb02d0, 0x49, 0x99c78300,
9a03e090, 0x2a, ...)
06-06 16:38:16.306 E/Go      (27757):   /Users/skydevin/go/src/github.com/QOSGroup/litewallet/litewallet/eth/transfer.go:30 +0
06-06 16:38:16.306 E/Go      (27757): github.com/QOSGroup/litewallet/litewallet.EthTransferETH(0x99eb02d0, 0x49, 0x99c78300, 0
a03e090, 0x2a, ...)
06-06 16:38:16.307 E/Go      (27757):   /Users/skydevin/go/src/github.com/QOSGroup/litewallet/litewallet/cshare.go:319 +0x94
06-06 16:38:16.307 E/Go      (27757): main.proxylitewallet__EthTransferETH(0xd040b2c0, 0x49, 0xd046d700, 0x3b, 0xd08e64f8, 0x1
06-06 16:38:16.307 E/Go      (27757):   /tmp/gomobile-work-901923068/src/gobind/go_litewalletmain.go:367 +0x180
06-06 16:38:16.307 E/Go      (27757): main._cgoexpwrap_7acd3932b608_proxylitewallet__EthTransferETH(0xd040b2c0, 0x49, 0xd046d7
, 0xb9f2a0c0, 0x2a, ...)
06-06 16:38:16.307 E/Go      (27757):   _cgo_gotypes.go:590 +0xcc

**Comment by MattWangming** [comment]
this issue was reproduced in one single process with 2 repeated operation:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x8e96c1]

goroutine 21 [running]:
testing.tRunner.func1(0xc0000c8300)
	C:/Go/src/testing/testing.go:792 +0x38e
panic(0x9c8380, 0x933d70)
	C:/Go/src/runtime/panic.go:513 +0x1c7
github.com/QOSGroup/litewallet/litewallet/eth.TransferETH(0xc000056be0, 0x11, 0xa7cf54, 0x3b, 0xa6366b, 0x8, 0xa6386b, 0x8, 0xa7712f, 0x2a, ...)
	D:/MattGO/src/github.com/QOSGroup/litewallet/litewallet/eth/transfer.go:30 +0xa1
github.com/QOSGroup/litewallet/litewallet/eth.TestTransferETH(0xc0000c8300)
	D:/MattGO/src/github.com/QOSGroup/litewallet/litewallet/eth/rpc_test.go:34 +0x1ae
testing.tRunner(0xc0000c8300, 0xbcfc78)
	C:/Go/src/testing/testing.go:827 +0xc6
created by testing.(*T).Run
	C:/Go/src/testing/testing.go:878 +0x35a

Process finished with exit code 1

```

**Comment by MattWangming** [comment]
similar to this issue in tendermint [Initializing DB failed when do duplicate query with verifier in the same process on tendermint v0.30.0](https://github.com/tendermint/tendermint/issues/3335)
need to do deep investigation on level DB processing!

**Comment by MattWangming** [comment]
https://github.com/QOSGroup/litewallet/blob/e381540f04244fe310b98f3f0c9f841cf9ee476d/litewallet/eth/local.go#L287
