### ISSUE TITLE
token transfer error

### ISSUE THREAD

**Issue by yangchuang64** [QOSGroup/litewallet#24]
transfer token fail, tansfer 5 qos,the amount is 500,000,000,000,000 in https://etherscan.io/

Token Transfer:
Pending Transfer to 0x2ecfea7fa8826d080c8d1ce93098bcede7425318For 500,000,000,000,000 ERC-20 (QOS Token)

[https://etherscan.io/tx/0x248bf85269ff06a246a253521dcf548d90ff45bc46f07467f0a29238c8616e53](url)

**Comment by MattWangming** [comment]
It is a bug in the ERC20 transfer function. 
The decimals should be taken into consideration on tokens specific setting. e.g. the QOS token in the issue is only 4 decimals not the default 18 decimals.
