### ISSUE TITLE
"LitewalletEthGetErc20Account" interface  error: abi: cannot marshal in to go slice: offset

### ISSUE THREAD

**Issue by wanghao926** [QOSGroup/litewallet#33]
when i Import Erc20 token: "EOS",

"LitewalletEthGetErc20Account" interface reports error: "abi: cannot marshal in to go slice: offset"

**Comment by MattWangming** [comment]
EOS Mainnet launched on June 1, 2018, and all ERC-20 based EOS tokens are swapped to the EOS Mainnet.
However, the ABI interface should be taken into consideration on its compliant with all ERC20 token standards.

**Comment by MattWangming** [comment]
more detailed info on this part:
```
abi: cannot marshal in to go slice: offset 31349740315309656776590804640418172219439600224308797316035737319045528027168 would go over slice boundary (len=32)
```
It is that the `symbol` in EOS contract is `bytes32`, while the code in the latest abi take it as type of `string`
This may lead to the conflict.

**Comment by MattWangming** [comment]
Closed with positive feedback~
