### ISSUE TITLE
cosmos hub-3 upgrading supported 

### ISSUE THREAD

**Issue by ewagmig** [QOSGroup/litewallet#39]
https://cosmos.bigdipper.live/proposals/14
The cosmos hub-3 upgrading is coming, a new branch corresponding to this is under development. 
There could be high priority on it due its deadline.

**Comment by MattWangming** [comment]
branch `dev-cosmosv35.0` is partially compatible and should be taken by rebase on it for the cosmos hub-3 version.

**Comment by MattWangming** [comment]
A new cosmos testnet based on latest version will be setup by @wangkuanzzu in issue #40 
Thanks for Kuan`s support on this upcoming upgrading.

**Comment by MattWangming** [comment]
Branch `dev-cosmosv37` is initiated to rebase on `master` for this restructuring. 
Qmoon explorer: http://192.168.1.223 for `gaiav2` information

**Comment by MattWangming** [comment]
Testnet info is in issue #40

**Comment by MattWangming** [comment]
Latest info on the proposal: https://cosmos.bigdipper.live/proposals/16
if passed, the upgrading time should be postponed to 24th Sep.
