### ISSUE TITLE
setup one cosmos testnet with latest version 

### ISSUE THREAD

**Issue by MattWangming** [QOSGroup/litewallet#40]
Due to the cosmoshub-3 upgrading plan on 15th Sep., a testnet should be established for testing below:

1. Mobile frontend 
2. Litewallet
3. Qmoon

**Comment by wangkuanzzu** [comment]
the testnet has finish , chain-id is gaiav2. and the testnet of gaia has three validators.
server ip:
192.168.1.184
192.168.1.236
192.168.1.238
![image](https://user-images.githubusercontent.com/20531573/64003568-15c32700-cb3f-11e9-8c7b-296e98553a41.png)
