### ISSUE TITLE
Feat: Increase gas to accelerate/cancel a pending transaction

### ISSUE THREAD

**Issue by blackpainter** [QOSGroup/litewallet#8]
We should add two buttons for a pending transaction: accelerate/cancel, then prompt the additional gas fee, and the possible failure in case of cancellation. This will make our life much more easier.

This article explains how it works: https://medium.com/@jgm.orinoco/releasing-stuck-ethereum-transactions-1390149f297d

**Comment by MattWangming** [comment]
Scenario clarified with FE requirement, a new function will be provided to Fetch the latest pending `nonce` at the current block height.
```
/get the nonce from the fromAddress to be dumped into tx
	nonce, err := client.PendingNonceAt(context.Background(), fromAddress)
	if err != nil {
		log.Fatal(err)
	}
```

**Comment by MattWangming** [comment]
error log when perform func **SpeedTransferETH**
```
Transaction gas price is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.
```

**Comment by MattWangming** [comment]
reproduce the issue above via SDK:
SDK侧有日志=== RUN   TestSpeedTransferETH
2019/06/06 11:27:44 Transaction gas price is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.

**Comment by MattWangming** [comment]
加速，前端输入做限制，只能增加gasPrice，不能减少。
@wanghao926 @yangchuang64

**Comment by MattWangming** [comment]
closed with positive feedback.
